### ISSUE TITLE
[Suggestion] Feeding camels cacti

### ISSUE THREAD

**Issue by Inonedn** [TeamMetallurgy/Atum2#123]
In real life, camels can eat cacti, it would be a neat way to heal them/breed them

**Comment by Shadowclaimer** [comment]
Cacti are not available in Atum because its based on the Sarahan Desert and Egypt.

This map shows where Cacti are found. Green being almost all other kinds, Blue being a very specific kind.

![image](https://user-images.githubusercontent.com/2214143/58385668-ea152b80-7fa8-11e9-909a-cac5127fa383.png)
