### ISSUE TITLE
Encounter DesertWolf CTD 

### ISSUE THREAD

**Issue by nextekoz** [TeamMetallurgy/Atum2#157]
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean

Client Versions:

- MC 1.12.2
- Forge Mod Loader 8.0.99.99
- Forge 14.23.5.2838
- Patchouli 1.0-20
- Baubles 1.5.2
- Atum2 1.12.2-2.0.15

Biome: DeadwoodForest

Encountered a Desert Wolf while running on foot - daylight, CTD (see attached report)
- Previous encounters with wolf and alpha, both were hostile (night) - successfully tamed with bone.

Admin entered game, entered dimension and approached same coords with same result.

[crash-2019-11-01_04.04.48-client.txt](https://github.com/TeamMetallurgy/Atum2/files/3795223/crash-2019-11-01_04.04.48-client.txt)

**Comment by JoelZBub** [comment]
Here is the server admin's crashlog for this issue. 
https://paste.ee/p/S6stp

No information was given in the server console when client crashed.

**Comment by GirafiStudios** [comment]
Thanks for the report!
The issue have previously been reported here https://github.com/TeamMetallurgy/Atum2/issues/94
It's caused by another mod corrupting the DataManager system (Used to hold various data for the entity). Unfortunately there is no good way to figure out what mod is causing it besides trying to track down what mod it is by trial and error.
Comparing your sets of mods with the sets of mods the other guy with the same issue was using might help you track down what mod is causing it.
If you figure it out, please let me know :)
