### ISSUE TITLE
reoccurring crash on valhelsia 2

### ISSUE THREAD

**Issue by coffeeordeath** [TeamMetallurgy/Atum2#199]
Im going to leave gists here instead of pastebins as the logs are too large. 
Debug.log - https://gist.github.com/coffeeordeath/01c32fd4085d72f4f55f25a01f8321a4
Latest.log - https://gist.github.com/coffeeordeath/4c30e899ecfb6ff603dd18ef33af482b
Crash Log - https://gist.github.com/coffeeordeath/adfa956c18d09a0ab912252917b709c3

This crash keeps happening and the "fix" is to delete the dimension data stored in level.dat

even after doing this, eventually the issue returns and it needs to be done again.

I believe after looking through the closed issues, #188 is the same or similar to my issue.

**Comment by GirafiStudios** [comment]
Unfortunately it's a bug in Forge, as you probably already know from having attempted the NBT removing fix.
I would suggest trying to do the NBT fix again & then turn off the sandstorm in the config, as it's what is being saved to the dimension even once in a while.

**Comment by coffeeordeath** [comment]
ok, thanks for the extremely fast response! ill try that out and keep my fingers crossed

**Comment by coffeeordeath** [comment]
I did what you suggested and let my players know to try heading to atum to test. We got a crash for ticking entity, which i posted as #200 and then on reboot, got this same crash again and had to delete the dimension data again.

**Comment by GirafiStudios** [comment]
Alright, thanks for trying it 👍 
Looking into the other crash atm.

**Comment by Vaelzan** [comment]
You can probably work around the issue on the mod side by storing the data in a different way, which you may need to do if Forge doesn't fix it on their end anytime soon (since this is happening incredibly frequently - am now seeing crash reports a couple of times per day since people started to use the dimension).

**Comment by Vaelzan** [comment]
There hasn't been another Forge update for 1.15.2 since I last commented three weeks ago so I suspect that despite being a bug on their end it will need to be handled inside the mod by changing how the data is stored. 

I'm still getting a lot of reports about crashes because of this and people having to edit level.dat to fix their worlds.

**Comment by GirafiStudios** [comment]
I do plan to figure out a workaround on our end, I've not forgotten about it.

**Comment by Vaelzan** [comment]
![unknown-40](https://user-images.githubusercontent.com/6418846/90335800-bc3b5d00-e01a-11ea-97aa-a1d606abb9fa.png)

![unknown-137](https://user-images.githubusercontent.com/6418846/90335807-c1001100-e01a-11ea-965d-be4bfe3e778a.png)

Something weird. I would expect the numeric dimension ID here to match? I'm not too familiar with custom dimensions so that might be a bad assumption but it does seem weird that Atum has an ID of 3 in one place and 4 in another?

**Comment by GirafiStudios** [comment]
Not really sure what you're talking about. From what you're showing The Midnight have ID 3 and Atum have ID 4

**Comment by Vaelzan** [comment]
The top picture shows Atum with 4, the bottom one shows Atum's DimensionData under 3. My assumption is that those numbers would match, but I also don't know if that's a valid assumption due to lack of knowledge in that area.

**Comment by GirafiStudios** [comment]
The attempted fix will be available in 2.1.5 on CurseForge shortly. The fix to remove the old dimension data (As described above) might still need to be applied first.
Please open a new issue, if you experience the crash on that version.
