### ISSUE TITLE
[1.12.2] Tefnut's Rain Causing Tick Lag

### ISSUE THREAD

**Issue by Ameranth** [TeamMetallurgy/Atum2#220]
Hello again,

Recently I raised this issue but it was closed, so here it is again with more evidence. [This is a quick video](https://drive.google.com/file/d/1VTD21JVLpoDtS8O6SgGIkJvS5DyVXDky/view?usp=sharing) showcasing the problem with _only Atum 2 with Forge_, the slowdown of ticks can clearly be seen as the bow is fired.

I hope this can help, you've done a great job with Atum!

**Comment by GirafiStudios** [comment]
So the only issue I see from that, is that after you've fired A LOT of arrows - the amount of arrows left on the ground will start causing lag. Is that what you're trying to show?

**Comment by Ameranth** [comment]
I'm not sure there seems to be some hostility here, I just want to help; in any case, this doesn't happen with normal arrows.

**Comment by GirafiStudios** [comment]
I'm not sure what've hostile about my previous message, I'm just trying to understand what you're trying to say/show. You're saying that "the slowdown of ticks can clearly been seen as the bow is fired". Everything seems when when the arrow is fired to me - but I'm most likely not looking at the correct thing in the Debug menu - all I see is the obvious lag when you at the end of the video have fired all the arrows, which is obviously a problem.

Yes, I was being hostile in the previous issue you opened and I apologize for that. Your last sentence just triggered me, because you said it in a demanding way and I'm tired of people constantly telling how X-mod I code for should be working or what features it should have, asking for updates etc.

**Comment by Ameranth** [comment]
I've also modded for projects in other games and I know how stressful it gets with a successful project, so I apologize for that, I never meant to come off that way.

To make the video shorter I sped it up and didn't stop to demonstrate the lag throughout the test, but the impact is visible in the pie-chart, as the section for ticks (purple) grows. But if this doesn't help reveal something reproduceable on your end then it's all good, I can understand what a nightmare it must be dealing with so many versions and systems.

Again thank you for your time, and your work!

**Comment by GirafiStudios** [comment]
Oh yea I definitely see the tick going up for each shot, that would just be because of the amount of arrows on the ground.
I'll look into making the arrows despawn quicker than normally (At least the ones you can't pick up anyways), so it's not possible to pile up that many arrows.
Unfortunately we don't support 1.12.2 anymore - and haven't for a good while now. It'll be fixed in an upcoming version for 1.16.4 though.

Appreciate your kind words :)

**Comment by Ameranth** [comment]
Sounds good, best of luck!

**Comment by sscards55** [comment]
ok so I have an for this, 
what if you keep a list of arrow that each player fired, this way you can simply remove old arrows when a new one is fired, setting a hard limit on how many arrows can exist in the world per player. One of the pros for this is that arrow can exist for their full duration unless more are fired.

3 different issue I came up with for this method depending on how you implement it, when the server shuts down and restarts, are:
1 the list no longer exits, leaving the arrows in the world for their full duration
2. the arrows despawn
3. you have to put in a lot of work for tracking each arrow, when it spawns, despawns, unloads, loads, or is removed from the world some other way.
