### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Entity9999** [TeamMetallurgy/Atum2#281]
Game crashes right after 9-10 secs have passed in atum. I have other 20 mods installed. I have already passed 1 month playing Atum 2 and nithing happened but recently the screen freezes and causing it a crash over and over again
[latest.log](https://github.com/TeamMetallurgy/Atum2/files/6604597/latest.log)
[latest.log](https://github.com/TeamMetallurgy/Atum2/files/6604601/latest.log)

 just when I enter Atum dimension.

Game version : 1.16.5 forgeoptifine and latest Atum 2 version

**Comment by GirafiStudios** [comment]
There is a lot of Optifine errors, so that's most likely the cause here.

**Comment by Entity9999** [comment]
So what's the solution remove optifine or use older versions?

**Comment by GirafiStudios** [comment]
Try removing Optifine.

**Comment by Entity9999** [comment]
[latest.log](https://github.com/TeamMetallurgy/Atum2/files/6609580/latest.log)
it crashed again....This time there wasnt optifine

**Comment by Entity9999** [comment]
Can I play it with optifine somehow again? 
And (sorry if I sound like dumb) what is the solution now....don't enter atum until next update?

**Comment by GirafiStudios** [comment]
Should be fine to play with Optifine :)
You probably sent me the wrong logs originally, is my best guess. As Atum was not mentioned at all, besides it loading up.
Yes, that's the "solution" for now.

**Comment by TopPercentageRattata** [comment]
I had almost the exact same issue in the past. Was biome ID layer 121 instead of 54 but aside from that was the same.
Was caused by having a mod that added a biome, atum somehow had that biome appear in Atum dimension so I removed that mod(Was voidscape beta from TF server), and then going in certain areas crashed the game with that msg in both the overworld and Atum. I had managed to fix it for the overworld by making a new world with same seed and only copying my base over with MCA selector, and then the issue only occured in Atum.
The Caused by: java.lang.IllegalStateException: Unknown biome id emitted by layers
thingie means a biome wasnt recoreded properly and then was removed I think, though it's odd how the error can occur in Atum dimension only even when issue is fixed for overworld

**Comment by sscards55** [comment]
Which launcher are you using?

**Comment by Entity9999** [comment]
Tlauncher

**Comment by sscards55** [comment]
That's quite unfortunate.

**Comment by Shadowclaimer** [comment]
We offer no support for Tlauncher issues.
