### ISSUE TITLE
Sometimes when crates don't close and autosave occurs, internal server locks up.

### ISSUE THREAD

**Issue by Kaleidio** [TeamMetallurgy/Atum2#355]
1.16.5
forge 36.2.4
atum (pretty much any...)

sometimes crates don't shut their lids, usually if you exit the inventory screen using some key other than whatever is bound to "view inventory" (E)

when the server (internal ones on singleplayer as well) attempt to save chunks it seems this causes the server to lockup and bring the game to a softlock state.  it might be occuring on multiplayer too but I did not check

the log does not provide any information on this.

**Comment by GirafiStudios** [comment]
That Crates don´t always close, is the same that causes vanilla chests to have the same issue.
This can often be caused by lag, or other issues in general. By the sounds of what you´re saying, something else is most likely causing problems - and when those problems occur the Crates lids don´t close as a result of it.

In any case, can´t do anything with the information you´ve provided, as there is zero way to reproduce it, with what you´ve said.

**Comment by Kaleidio** [comment]
so either that or something with your dimension is causing lag that doesn't happen in every other dimension in my pack
