### ISSUE TITLE
Blocks & Items aren't in their respective categories in the recipe book

### ISSUE THREAD

**Issue by CREEATION** [TeamMetallurgy/Atum2#80]
Title, pretty much. They all seem to be under the same tab:

![2019-03-30_21 06 11](https://user-images.githubusercontent.com/3277769/55281103-d98d5f80-532f-11e9-8962-5a8cd45226f6.png)
![2019-03-30_21 07 45](https://user-images.githubusercontent.com/3277769/55281107-e14d0400-532f-11e9-9755-ab94004408ac.png)

**Comment by GirafiStudios** [comment]
I'm not familiar with the recipe book. So I have no clue what I'm looking at.

**Comment by CREEATION** [comment]
I'm not sure what to answer. It's the vanilla recipe book, which is basically a very basic "creative tabs" for survival, transfering recipes to the crafting grid when you click on them.

**Comment by GirafiStudios** [comment]
So the categories in the recipe book gets its content based on the Creative Tabs?

**Comment by CREEATION** [comment]
I'm not familiar with the code behind the inner workings of the recipe book.

**Comment by GirafiStudios** [comment]
After looking into it a bit, I've discovered the following:
The Recipe Book tabs contains the same items/blocks as the creative tabs. For the Creative Tabs that does not match the 3 defined one is all thrown into "Misc"
Atum have its own Creative Tab with all its items/blocks, which is why it's thrown into "Misc" in the recipe book. 
As mentioned here https://github.com/MinecraftForge/MinecraftForge/issues/4601 , there is no way to change this in Forge atm.

**Comment by CREEATION** [comment]
Oh boy. Thanks for looking into it.
